# MODEL:
#   NAME: 'SimpleBaseline'
#   SAVE_NAME: "SimpleBaseline_local"
# MODEL:
#   NAME: 'EfficientNetLite'
#   SAVE_NAME: "EfficientNet_lite0_local"
#   SIZE: 0
MODEL:
  NAME: 'EvoPose2D_transfer'
  SAVE_NAME: "EvoPose2D_XS_transfer"
  SIZE: XS


TRAIN:
  BATCH_SIZE: 2
  EPOCHS: 2
  WARMUP_EPOCHS: 5
  WARMUP_FACTOR: 0.1
  LR: 0.00025
  LR_SCHEDULE: 'warmup_cosine_decay'

VAL:
  BATCH_SIZE: 2

DATASET:
  INPUT_SHAPE: [256, 192, 3]
  OUTPUT_SHAPE: [64, 48, 23]
  TRAIN_DIR: 'train_test'
  TRAIN_SIZE: 10
  VAL_DIR: 'val_test'
  VAL_SIZE: 5
  FLIP_PROB: 0.5
  CONTRAST_PROB: 0.5
  HUE_PROB: 0.5